from __future__ import annotations

"""Canonical raw theorem-parameter verifier for the v16 P1/P2 package.

The packet is not an empirical proof that the declared hit probabilities or
calibration cases are generated by a particular real-world population.  It is
a strict theorem-instantiation artifact: every numerical child certificate is
recomputed from canonical exact inputs, and the packet is bound to one P0 raw
execution context.
"""

from dataclasses import asdict, dataclass
from fractions import Fraction
import hashlib
import json
from pathlib import Path
from typing import Mapping

from .pareto_finite_menu_generalization import (
    FiniteMenuGeneralizationCertificate,
    certify_finite_menu_generalization,
)
from .pareto_frozen_cells import parse_canonical_fraction
from .pareto_intrinsic_dimension import (
    IntrinsicDimensionCertificate,
    certify_ordered_bilipschitz_reference_family,
)
from .pareto_shared_categorical_design import (
    RationalTransportationLowerBound,
    SharedCategoricalIdentificationCertificate,
    SharedConfirmAllocationCertificate,
    certify_shared_categorical_identification_upper_bound,
    exact_shared_confirm_allocation,
    rational_pairwise_transportation_lower_bound,
)
from .pareto_v16_artifact_bundle import (
    V16ComposedArtifactCertificate,
    canonical_json_bytes,
    verify_v16_composed_bundle,
)

V16_THEORY_PACKET_SCHEMA = "pareto_v16_raw_theory_parameter_packet_v2"
V16_THEORY_CERTIFICATE_SCHEMA = "pareto_v16_raw_theory_parameter_certificate_v2"


class V16TheoryPacketError(ValueError):
    pass


def _strict_object(pairs: list[tuple[str, object]]) -> dict[str, object]:
    result: dict[str, object] = {}
    for key, value in pairs:
        if key in result:
            raise V16TheoryPacketError(f"Duplicate JSON key {key!r}.")
        result[key] = value
    return result


def _mapping(value: object, *, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise V16TheoryPacketError(f"{label} must be a JSON object.")
    return value


def _sequence(value: object, *, label: str) -> list[object]:
    if not isinstance(value, list):
        raise V16TheoryPacketError(f"{label} must be a JSON array.")
    return value


def _keys(value: Mapping[str, object], expected: set[str], *, label: str) -> None:
    observed = set(value)
    if observed != expected:
        raise V16TheoryPacketError(
            f"{label} keys differ: missing={sorted(expected-observed)}, "
            f"extra={sorted(observed-expected)}."
        )


def _positive_int(value: object, *, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise V16TheoryPacketError(f"{label} must be a positive integer.")
    return value


def _cell_id(cell: tuple[int, ...]) -> str:
    return ",".join(str(value) for value in cell)


def _exact_probability_matrix(
    value: object,
) -> dict[str, dict[str, str]]:
    raw = _mapping(value, label="probability_matrix")
    if not raw:
        raise V16TheoryPacketError("probability_matrix must be nonempty.")
    result: dict[str, dict[str, str]] = {}
    cells: set[str] | None = None
    for type_id in sorted(raw):
        if not isinstance(type_id, str) or not type_id:
            raise V16TheoryPacketError("Probability type IDs must be nonempty text.")
        row = _mapping(raw[type_id], label=f"probability_matrix[{type_id}]")
        if not row:
            raise V16TheoryPacketError("Every probability row must be nonempty.")
        current_cells = set(row)
        if cells is None:
            cells = current_cells
        elif current_cells != cells:
            raise V16TheoryPacketError("All probability rows must use the same cells.")
        resolved: dict[str, str] = {}
        total = Fraction(0)
        for cell in sorted(row):
            if not isinstance(cell, str) or not cell:
                raise V16TheoryPacketError("Cell IDs must be nonempty text.")
            probability = parse_canonical_fraction(
                row[cell], label=f"probability_matrix[{type_id},{cell}]"
            )
            if probability < 0 or probability > 1:
                raise V16TheoryPacketError("Cell probabilities must lie in [0,1].")
            total += probability
            resolved[cell] = str(row[cell])
        if total > 1:
            raise V16TheoryPacketError(
                f"Probability row for {type_id!r} exceeds one."
            )
        result[type_id] = resolved
    return result


def _reference_points(value: object) -> tuple[tuple[Fraction, ...], ...]:
    raw = _sequence(value, label="intrinsic.reference_points")
    if len(raw) < 2:
        raise V16TheoryPacketError("At least two intrinsic reference points are required.")
    result: list[tuple[Fraction, ...]] = []
    dimension: int | None = None
    for index, point_raw in enumerate(raw):
        point_values = _sequence(point_raw, label=f"intrinsic.reference_points[{index}]")
        if dimension is None:
            dimension = len(point_values)
        if dimension is None or dimension <= 0 or len(point_values) != dimension:
            raise V16TheoryPacketError("Intrinsic reference points have inconsistent dimension.")
        result.append(
            tuple(
                parse_canonical_fraction(
                    coordinate,
                    label=f"intrinsic.reference_points[{index}][{coordinate_index}]",
                )
                for coordinate_index, coordinate in enumerate(point_values)
            )
        )
    return tuple(result)


@dataclass(frozen=True)
class V16TheoryParameterCertificate:
    schema: str
    packet_sha256: str
    composed_packet_sha256: str
    context_sha256: str
    shared_identification: SharedCategoricalIdentificationCertificate
    shared_confirm_allocation: SharedConfirmAllocationCertificate
    transportation_lower_bounds: tuple[RationalTransportationLowerBound, ...]
    finite_menu_generalization: FiniteMenuGeneralizationCertificate
    intrinsic_dimension: IntrinsicDimensionCertificate
    all_children_recomputed_from_raw_exact_inputs: bool
    probability_matrix_status: str
    theorem_scope: str

    def to_jsonable(self) -> dict[str, object]:
        return {
            "schema": self.schema,
            "packet_sha256": self.packet_sha256,
            "composed_packet_sha256": self.composed_packet_sha256,
            "context_sha256": self.context_sha256,
            "shared_identification": self.shared_identification.to_jsonable(),
            "shared_confirm_allocation": self.shared_confirm_allocation.to_jsonable(),
            "transportation_lower_bounds": [
                item.to_jsonable() for item in self.transportation_lower_bounds
            ],
            "finite_menu_generalization": self.finite_menu_generalization.to_jsonable(),
            "intrinsic_dimension": self.intrinsic_dimension.to_jsonable(),
            "all_children_recomputed_from_raw_exact_inputs": (
                self.all_children_recomputed_from_raw_exact_inputs
            ),
            "probability_matrix_status": self.probability_matrix_status,
            "theorem_scope": self.theorem_scope,
        }


def _reference_points_from_composed_bundle(path: str | Path) -> tuple[tuple[Fraction, ...], ...]:
    raw = Path(path).read_bytes()
    payload = json.loads(raw.decode("utf-8"), object_pairs_hook=_strict_object)
    root = _mapping(payload, label="composed_bundle")
    reference = _mapping(root.get("reference_plan"), label="composed_bundle.reference_plan")
    raw_points = _sequence(reference.get("reference_points"), label="reference_points")
    points: list[tuple[Fraction, ...]] = []
    for index, point in enumerate(raw_points):
        values = _sequence(point, label=f"reference_points[{index}]")
        points.append(
            tuple(
                parse_canonical_fraction(value, label=f"reference_points[{index}][{i}]")
                for i, value in enumerate(values)
            )
        )
    return tuple(points)


def verify_v16_theory_packet(
    theory_packet_path: str | Path,
    *,
    composed_bundle_path: str | Path,
) -> tuple[V16TheoryParameterCertificate, V16ComposedArtifactCertificate]:
    composed = verify_v16_composed_bundle(composed_bundle_path)
    raw = Path(theory_packet_path).read_bytes()
    try:
        payload = json.loads(raw.decode("utf-8"), object_pairs_hook=_strict_object)
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise V16TheoryPacketError("Theory packet is not strict UTF-8 JSON.") from error
    if raw != canonical_json_bytes(payload):
        raise V16TheoryPacketError("Theory packet is not canonical JSON.")
    root = _mapping(payload, label="theory_packet")
    _keys(
        root,
        {
            "schema",
            "composed_packet_sha256",
            "context_sha256",
            "probability_matrix",
            "identification_error",
            "max_rounds",
            "transport_error",
            "transport_log_series_terms",
            "confirm_union_miss_budget",
            "max_assignments",
            "max_total_confirm_replicas",
            "finite_menu",
            "intrinsic",
            "probability_matrix_status",
        },
        label="theory_packet",
    )
    if root["schema"] != V16_THEORY_PACKET_SCHEMA:
        raise V16TheoryPacketError("Unexpected theory packet schema.")
    if root["composed_packet_sha256"] != composed.packet_sha256:
        raise V16TheoryPacketError("Theory packet is bound to a different composed packet.")
    if root["context_sha256"] != composed.context_sha256:
        raise V16TheoryPacketError("Theory packet is bound to a different context.")
    status = root["probability_matrix_status"]
    if status not in {"theorem_parameter", "independently_source_certified"}:
        raise V16TheoryPacketError("Unsupported probability_matrix_status.")
    probability_matrix = _exact_probability_matrix(root["probability_matrix"])
    type_ids = set(probability_matrix)
    composed_type_ids = {endpoint.type_id for endpoint in composed.pilot_result.endpoints}
    if type_ids != composed_type_ids:
        raise V16TheoryPacketError("Theory probability types differ from the P0 packet.")
    matrix_cells = set(next(iter(probability_matrix.values())))
    composed_cells = {_cell_id(item.cell) for item in composed.selected_cells}
    if matrix_cells != composed_cells:
        raise V16TheoryPacketError("Theory probability cells differ from certified P0 cells.")
    identification = certify_shared_categorical_identification_upper_bound(
        probability_matrix,
        familywise_error=root["identification_error"],
        max_rounds=_positive_int(root["max_rounds"], label="max_rounds"),
    )
    confirm = exact_shared_confirm_allocation(
        probability_matrix,
        union_miss_budget=root["confirm_union_miss_budget"],
        max_assignments=_positive_int(root["max_assignments"], label="max_assignments"),
        max_total_replicas=_positive_int(
            root["max_total_confirm_replicas"], label="max_total_confirm_replicas"
        ),
    )
    transport_error = root["transport_error"]
    series_terms = _positive_int(
        root["transport_log_series_terms"], label="transport_log_series_terms"
    )
    lower_bounds: list[RationalTransportationLowerBound] = []
    for cell_bound in identification.cell_bounds:
        best_type = cell_bound.best_type
        ranking = sorted(
            (
                (parse_canonical_fraction(probability_matrix[type_id][cell_bound.cell_id],
                                          label="probability"), type_id)
                for type_id in identification.type_ids
            ),
            key=lambda item: (-item[0], item[1]),
        )
        for challenger_probability, challenger_type in ranking[1:]:
            lower_bounds.append(
                rational_pairwise_transportation_lower_bound(
                    cell_id=cell_bound.cell_id,
                    best_type=best_type,
                    challenger_type=challenger_type,
                    best_probability=ranking[0][0],
                    challenger_probability=challenger_probability,
                    error_probability=transport_error,
                    log_series_terms=series_terms,
                )
            )
    finite_menu_raw = _mapping(root["finite_menu"], label="finite_menu")
    _keys(
        finite_menu_raw,
        {"confidence_error", "losses_by_design"},
        label="finite_menu",
    )
    losses_raw = _mapping(finite_menu_raw["losses_by_design"], label="losses_by_design")
    losses = {
        design: tuple(
            parse_canonical_fraction(value, label=f"loss[{design},{index}]")
            for index, value in enumerate(_sequence(row, label=f"losses[{design}]"))
        )
        for design, row in losses_raw.items()
    }
    finite_menu = certify_finite_menu_generalization(
        losses,
        confidence_error=finite_menu_raw["confidence_error"],
    )
    intrinsic_raw = _mapping(root["intrinsic"], label="intrinsic")
    _keys(
        intrinsic_raw,
        {"reference_points", "lower_constant", "upper_constant", "tau"},
        label="intrinsic",
    )
    intrinsic_points = _reference_points(intrinsic_raw["reference_points"])
    composed_reference_points = _reference_points_from_composed_bundle(composed_bundle_path)
    if intrinsic_points != composed_reference_points:
        raise V16TheoryPacketError(
            "Intrinsic reference family differs from the P0 frozen reference plan."
        )
    intrinsic = certify_ordered_bilipschitz_reference_family(
        intrinsic_points,
        lower_constant=parse_canonical_fraction(
            intrinsic_raw["lower_constant"], label="lower_constant"
        ),
        upper_constant=parse_canonical_fraction(
            intrinsic_raw["upper_constant"], label="upper_constant"
        ),
        tau=parse_canonical_fraction(intrinsic_raw["tau"], label="tau"),
    )
    return (
        V16TheoryParameterCertificate(
            schema=V16_THEORY_CERTIFICATE_SCHEMA,
            packet_sha256=hashlib.sha256(raw).hexdigest(),
            composed_packet_sha256=composed.packet_sha256,
            context_sha256=composed.context_sha256,
            shared_identification=identification,
            shared_confirm_allocation=confirm,
            transportation_lower_bounds=tuple(lower_bounds),
            finite_menu_generalization=finite_menu,
            intrinsic_dimension=intrinsic,
            all_children_recomputed_from_raw_exact_inputs=True,
            probability_matrix_status=str(status),
            theorem_scope=(
                "canonical_supplied_reference_independent_endpoint_branch;"
                "probability_matrix_is_an_explicit_theorem_parameter_or_independent_source_certificate"
            ),
        ),
        composed,
    )


def write_canonical_v16_theory_packet(
    path: str | Path,
    payload: Mapping[str, object],
) -> str:
    raw = canonical_json_bytes(dict(payload))
    Path(path).write_bytes(raw)
    return hashlib.sha256(raw).hexdigest()


__all__ = [
    "V16_THEORY_CERTIFICATE_SCHEMA",
    "V16_THEORY_PACKET_SCHEMA",
    "V16TheoryPacketError",
    "V16TheoryParameterCertificate",
    "verify_v16_theory_packet",
    "write_canonical_v16_theory_packet",
]
